# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/digital_twin.xdc

# IP: ip/DRAM_1/DRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DRAM || ORIG_REF_NAME==DRAM} -quiet] -quiet

# IP: ip/IROM_1/IROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IROM || ORIG_REF_NAME==IROM} -quiet] -quiet
