# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mingzhenjia/Complex-CPU-Design-Based-on-RISC-V/RISC-V CPU/RISC-V CPU.srcs/sources_1/ip/MEMORY/MEMORY.xci
# IP: The module: 'MEMORY' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mingzhenjia/Complex-CPU-Design-Based-on-RISC-V/RISC-V CPU/RISC-V CPU.gen/sources_1/ip/MEMORY/MEMORY_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEMORY'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mingzhenjia/Complex-CPU-Design-Based-on-RISC-V/RISC-V CPU/RISC-V CPU.srcs/sources_1/ip/MEMORY/MEMORY.xci
# IP: The module: 'MEMORY' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mingzhenjia/Complex-CPU-Design-Based-on-RISC-V/RISC-V CPU/RISC-V CPU.gen/sources_1/ip/MEMORY/MEMORY_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEMORY'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
